-- Reference seed: no users/passwords. Assign active admins manually in clinic project.
insert into public.settings(key,value) values
('popup','{"title":"","text":"","active":false,"startsAt":null,"endsAt":null}'),
('contact','{"whatsapp":"5521985601000","message":"Olá, encontrei o site da Clínica de Olhos Benchimol em uma busca e gostaria de mais informações"}')
on conflict(key) do nothing;
insert into public.reserved_routes(path) values
('/'),
('/admin/'),
('/api/'),
('/blog/'),
('/catarata/'),
('/category/'),
('/certificacoes/'),
('/cirurgia-refrativa/'),
('/convenios/'),
('/degeneracao-macular/'),
('/dr-amir-zisman/'),
('/dr-eduardo-lessa-martinez/'),
('/dr-eliezer-benchimol/'),
('/dr-gabriel-benchimol/'),
('/dr-luciano-galhardo-de-barros/'),
('/dr-paulo-de-heraclito-lima-filho/'),
('/dr-raphael-lima-benchimol/'),
('/dr-sergio-benchimol-old/'),
('/dr-sergio-benchimol/'),
('/dra-adriana-benchimol/'),
('/dra-amelia-gomes-de-souza/'),
('/dra-dilma-de-sa-cavalcanti-do-vale/'),
('/dra-francine-campos-hauck/'),
('/dra-liana-benchimol/'),
('/dra-mirelle-benchimol/'),
('/dra-monica-de-oliveira-coelho/'),
('/dra-nina-benchimol/'),
('/dra-veronica-benchimol/'),
('/equipamentos/'),
('/equipe/'),
('/especialidades/'),
('/exames-e-procedimentos/'),
('/faq-perguntas-frequentes/'),
('/glaucoma/'),
('/instalacoes/'),
('/insternacional/'),
('/olho-seco/'),
('/retinopatia-diabetica/'),
('/robots.txt/'),
('/sample-page/'),
('/servicos/'),
('/sitemap.xml/'),
('/sobre-nos/'),
('/tag/'),
('/wp-admin/'),
('/wp-content/'),
('/wp-json/')
on conflict do nothing;
