'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useState } from 'react';
import { adminRequest } from '@/lib/admin/api';
const links = [ ['/admin', 'Início', '⌂'], ['/admin/posts', 'Posts', '▤'], ['/admin/midias', 'Mídias', '▧'], ['/admin/aviso', 'Aviso do site', '◉'], ['/admin/contato', 'WhatsApp', '◌'], ['/admin/prompts', 'Prompts', '✎'] ];
export function AdminShell({ name, children }: { name: string; children: React.ReactNode }) {
  const path = usePathname(), router = useRouter(); const [menu, setMenu] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function logout() { if (!window.dispatchEvent(new Event('admin-before-leave', { cancelable: true }))) return; setBusy(true); setError(''); try { await adminRequest('/api/auth/logout', { method: 'POST' }); router.replace('/admin/login'); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível sair.'); setBusy(false); } }
  return <div className="admin-root admin-shell"><a className="admin-skip" href="#admin-content">Ir para o conteúdo</a><aside id="admin-mobile-nav" className={`admin-sidebar ${menu ? 'admin-sidebar-open' : ''}`}><Link href="/admin" className="admin-brand"><span className="admin-brand-mark" aria-hidden="true">B</span><span>Benchimol<small>Administração do site</small></span></Link><nav aria-label="Administração">{links.map(([href, label, icon]) => <Link key={href} href={href} className={(href === '/admin' ? path === href : path.startsWith(href)) ? 'admin-nav-active' : ''} aria-current={(href === '/admin' ? path === href : path.startsWith(href)) ? 'page' : undefined} onClick={() => setMenu(false)}><span aria-hidden="true">{icon}</span>{label}</Link>)}</nav><div className="admin-sidebar-bottom"><a href="/" target="_blank" rel="noopener noreferrer">Abrir site <span aria-hidden="true">↗</span></a><small>Clínica de Olhos Benchimol</small></div></aside><div className="admin-workspace"><header className="admin-topbar"><button className="admin-menu-button admin-button admin-button-secondary" aria-expanded={menu} aria-controls="admin-mobile-nav" onClick={() => setMenu(!menu)}>{menu ? 'Fechar menu' : 'Menu'}</button><span className="admin-topbar-label">Painel do site</span><div className="admin-user"><span>{name}</span><button className="admin-text-button" disabled={busy} onClick={logout}>{busy ? 'Saindo…' : 'Sair'}</button></div></header>{error && <div className="admin-notice admin-notice-error" role="alert">{error}</div>}<main id="admin-content" className="admin-main" tabIndex={-1}>{children}</main><footer className="admin-footer">Os horários do painel são exibidos no fuso de São Paulo.</footer></div></div>;
}
