'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import type { Media, PageResult } from '@/lib/domain/types';
import { AdminApiError, adminRequest } from '@/lib/admin/api';
import { formatBytes, formatDate, validateUpload } from '@/lib/admin/helpers';
import { ConfirmDialog, EmptyState, ErrorPanel, Loading, Notice, PageHeading, Pager, useResource } from './ui';
export function MediaLibrary() {
  const [page, setPage] = useState(1), [q, setQ] = useState(''), [search, setSearch] = useState(''), [selected, setSelected] = useState<Media | null>(null), [uploadOpen, setUploadOpen] = useState(false), [message, setMessage] = useState('');
  const resource = useResource<PageResult<Media>>(`/api/admin/media?page=${page}&pageSize=18&q=${encodeURIComponent(search)}`);
  return <><PageHeading title="Mídias" description="Imagens, textos alternativos e arquivos já usados no site." action={<button className="admin-button" onClick={() => setUploadOpen(!uploadOpen)} aria-expanded={uploadOpen}>{uploadOpen ? 'Fechar envio' : 'Enviar imagem'}</button>} />{message && <Notice>{message}</Notice>}{uploadOpen && <UploadForm onSuccess={() => { setMessage('Imagem enviada para a biblioteca.'); setUploadOpen(false); resource.reload(); }} />}<form className="admin-filters" onSubmit={event => { event.preventDefault(); setSearch(q.trim()); setPage(1); }}><label className="admin-field">Buscar na biblioteca<input type="search" placeholder="Texto alternativo" value={q} onChange={event => setQ(event.target.value)} /></label><button className="admin-button admin-button-secondary">Buscar</button></form>{resource.loading ? <Loading /> : resource.error ? <ErrorPanel error={resource.error} retry={resource.reload} /> : resource.data?.items.length ? <><div className="admin-media-grid">{resource.data.items.map(media => <div className="admin-media-card" key={media.id}><button onClick={() => setSelected(media)} aria-label={`Editar ${media.alt || media.url.split('/').pop()}`}>{media.mimeType.startsWith('image/') ? <img src={media.url} alt={media.alt} className="admin-media-thumb" loading="lazy" /> : <span className="admin-media-pdf">Arquivo {media.mimeType === 'application/pdf' ? 'PDF' : ''}</span>}</button><div className="admin-media-info"><p title={media.url.split('/').pop()}>{media.alt || media.url.split('/').pop()}</p><small>{formatBytes(media.bytes)}{media.width && media.height ? ` · ${media.width} × ${media.height}` : ''}</small><small>{media.uses.length ? `Usada em ${media.uses.length} ${media.uses.length === 1 ? 'post' : 'posts'}` : 'Sem uso em posts registrado'}</small><div className="admin-actions"><button className="admin-text-button" onClick={() => setSelected(media)}>Ver detalhes</button><a href={media.url} target="_blank" rel="noopener noreferrer">Abrir arquivo</a></div></div></div>)}</div><Pager total={resource.data.total} page={resource.data.page} pageSize={resource.data.pageSize} onChange={setPage} /></> : <EmptyState title={search ? 'Nenhuma mídia encontrada' : 'A biblioteca ainda está vazia'}><p>{search ? 'Tente outro nome ou texto alternativo.' : 'Envie uma imagem JPG, PNG, WebP ou GIF para usar nos posts.'}</p></EmptyState>}{selected && <MediaDetails key={selected.id} media={selected} onClose={() => setSelected(null)} onChanged={text => { setSelected(null); setMessage(text); resource.reload(); }} />}</>;
}
function UploadForm({ onSuccess }: { onSuccess: () => void }) {
  const [file, setFile] = useState<File | null>(null), [alt, setAlt] = useState(''), [caption, setCaption] = useState(''), [error, setError] = useState<Error | null>(null), [busy, setBusy] = useState(false), [stage, setStage] = useState(''), [pendingId, setPendingId] = useState<string | null>(null);
  async function upload(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); if (!file) { setError(new Error('Escolha uma imagem para enviar.')); return; } const invalid = validateUpload(file); if (invalid) { setError(new Error(invalid)); return; } setBusy(true); setStage(pendingId ? 'Validando imagem…' : 'Preparando envio…'); try { if (pendingId) { await adminRequest<Media>(`/api/admin/media/${pendingId}/finalize`, { method: 'POST' }); onSuccess(); return; } const intent = await adminRequest<{ id: string; signedUrl: string }>('/api/admin/media/upload-url', { method: 'POST', body: JSON.stringify({ mimeType: file.type, bytes: file.size, alt, caption }) }); const multipart = new FormData(); multipart.append('cacheControl', '0'); multipart.append('', file); setStage('Enviando imagem…'); const uploaded = await fetch(intent.signedUrl, { method: 'PUT', body: multipart, headers: { 'x-upsert': 'false' }, credentials: 'omit', redirect: 'error' }); if (!uploaded.ok) throw new Error('Não foi possível enviar o arquivo. Tente novamente.'); setPendingId(intent.id); setStage('Validando imagem…'); await adminRequest<Media>(`/api/admin/media/${intent.id}/finalize`, { method: 'POST' }); onSuccess(); } catch (reason) { if (reason instanceof AdminApiError && ['validation', 'expired_upload'].includes(reason.code)) setPendingId(null); setError(reason instanceof Error ? reason : new Error('Não foi possível enviar a imagem.')); } finally { setBusy(false); } }
  return <section className="admin-card" style={{ marginBottom: 22 }}><h2 style={{ marginBottom: 16 }}>Enviar imagem</h2><form onSubmit={upload}><label className="admin-field">Arquivo<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" required disabled={busy || !!pendingId} onChange={event => { const value = event.target.files?.[0] ?? null; setFile(value); const invalid = value ? validateUpload(value) : null; setError(invalid ? new Error(invalid) : null); }} /><small>JPG, PNG, WebP ou GIF de até 10 MB. O formato também é verificado pelo servidor.</small></label><div className="admin-two-fields"><label className="admin-field">Texto alternativo<input value={alt} maxLength={500} disabled={busy || !!pendingId} onChange={event => setAlt(event.target.value)} /><small>Descreva o que a imagem mostra. Imagens decorativas podem ficar sem descrição.</small></label><label className="admin-field">Legenda (opcional)<input value={caption} maxLength={1000} disabled={busy || !!pendingId} onChange={event => setCaption(event.target.value)} /></label></div>{error && <ErrorPanel error={error} />}<button className="admin-button" disabled={busy || !file || !!file && !!validateUpload(file)}>{busy ? stage : pendingId ? 'Finalizar envio' : 'Enviar para biblioteca'}</button></form></section>;
}
function MediaDetails({ media, onClose, onChanged }: { media: Media; onClose: () => void; onChanged: (message: string) => void }) {
  const dialog = useRef<HTMLDialogElement>(null); const [alt, setAlt] = useState(media.alt), [caption, setCaption] = useState(media.caption), [busy, setBusy] = useState(false), [error, setError] = useState<Error | null>(null), [confirm, setConfirm] = useState(false);
  useEffect(() => { dialog.current?.showModal(); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await adminRequest<Media>(`/api/admin/media/${media.id}`, { method: 'PATCH', body: JSON.stringify({ alt, caption }) }); onChanged('Texto alternativo e legenda salvos. As imagens já inseridas nos posts mantêm os seus próprios textos.'); } catch (reason) { setError(reason instanceof Error ? reason : new Error('Não foi possível salvar.')); } finally { setBusy(false); } }
  async function remove() { setBusy(true); setError(null); try { const result = await adminRequest<{ storageCleanup?: string; message?: string }>(`/api/admin/media/${media.id}`, { method: 'DELETE' }); onChanged(result.message ?? 'Mídia excluída da biblioteca.'); } catch (reason) { setError(reason instanceof Error ? reason : new Error('Não foi possível excluir.')); setConfirm(false); } finally { setBusy(false); } }
  return <><dialog ref={dialog} className="admin-dialog" aria-labelledby="admin-media-details-title" onCancel={event => { if (busy) event.preventDefault(); else onClose(); }} onClose={onClose}><div className="admin-card-header"><h2 id="admin-media-details-title">Detalhes da mídia</h2><button className="admin-button admin-button-secondary" disabled={busy} onClick={onClose}>Fechar</button></div>{media.mimeType.startsWith('image/') && <img src={media.url} alt={alt} className="admin-cover" />}<p className="admin-muted">{media.mimeType} · {formatBytes(media.bytes)} · Cadastrada em {formatDate(media.createdAt)}</p><p><a href={media.url} target="_blank" rel="noopener noreferrer">Abrir arquivo original</a></p><form onSubmit={save} style={{ marginTop: 20 }}><label className="admin-field">Texto alternativo<input value={alt} maxLength={500} disabled={busy} onChange={event => setAlt(event.target.value)} /></label><label className="admin-field">Legenda<textarea value={caption} maxLength={1000} disabled={busy} onChange={event => setCaption(event.target.value)} /></label>{error && <ErrorPanel error={error} />}<div className="admin-actions"><button className="admin-button" disabled={busy}>{busy ? 'Salvando…' : 'Salvar detalhes'}</button><button type="button" className="admin-button admin-button-danger" disabled={busy || media.uses.length > 0 || !media.storagePath} onClick={() => setConfirm(true)}>Excluir mídia</button></div></form><h3 style={{ marginTop: 24 }}>Onde esta mídia aparece</h3>{!media.storagePath && <p className="admin-muted">Este arquivo legado é preservado pela migração. Sua exclusão exige revisão do responsável técnico.</p>}{media.uses.length ? <><p className="admin-muted">A exclusão está bloqueada enquanto houver referências. Remova ou troque a mídia nos conteúdos abaixo.</p><ul className="admin-list" style={{ marginTop: 12 }}>{media.uses.map(use => <li key={use.postId}><Link href={`/admin/posts/${use.postId}`}>{use.title}</Link></li>)}</ul></> : <p className="admin-muted">Nenhum uso em posts registrado. O servidor verifica novamente as referências antes de excluir.</p>}</dialog><ConfirmDialog open={confirm} title="Excluir esta mídia?" confirmLabel="Excluir mídia" danger busy={busy} onClose={() => { if (!busy) setConfirm(false); }} onConfirm={remove}><p>{media.url.split('/').pop()}</p><p>A exclusão do arquivo é permanente e só será permitida se o servidor confirmar que ele não está referenciado.</p></ConfirmDialog></>;
}
