'use client';
import { useState } from 'react';
import type { AdminPrompt } from '@/lib/admin/prompts';
import { Notice, PageHeading } from './ui';
export function PromptLibrary({ prompts }: { prompts: AdminPrompt[] }) {
  const [id, setId] = useState(prompts[0]?.id ?? ''), [message, setMessage] = useState(''), [error, setError] = useState(''); const selected = prompts.find(prompt => prompt.id === id);
  async function copy() { if (!selected) return; setMessage(''); setError(''); try { await navigator.clipboard.writeText(selected.text); setMessage('Prompt base e instrução da tarefa copiados. Preencha o pedido antes de usar.'); } catch { setError('O navegador não permitiu copiar. Selecione o texto abaixo e copie manualmente.'); } }
  return <><PageHeading title="Prompts" description="Instruções prontas para pedir alterações à IA que tenha acesso ao projeto." />{message && <Notice>{message}</Notice>}{error && <Notice kind="error">{error}</Notice>}<div className="admin-prompts"><nav className="admin-prompt-list" aria-label="Prompts disponíveis">{prompts.map(prompt => <button key={prompt.id} aria-pressed={id === prompt.id} onClick={() => { setId(prompt.id); setMessage(''); setError(''); }}><strong>{prompt.title}</strong><small>{prompt.category} · Versão {prompt.version}</small></button>)}</nav>{selected && <section className="admin-card"><div className="admin-card-header"><div><h2>{selected.title}</h2><p className="admin-muted">{selected.id} · Versão {selected.version}</p></div><button className="admin-button" onClick={copy}>Copiar prompt completo</button></div><p>O texto reúne as regras do projeto e a tarefa escolhida. Informe o que deseja mudar e forneça os arquivos de contexto se a IA não tiver acesso ao repositório.</p><textarea className="admin-prompt-text" aria-label="Prompt completo para copiar" readOnly value={selected.text} onFocus={event => event.target.select()} /><h3 style={{ marginTop: 22 }}>Arquivos de contexto</h3><ul className="admin-context-files">{selected.contextPaths.map(file => <li key={file}>{file}</li>)}</ul><p className="admin-muted">Esta biblioteca permite ler e copiar instruções. Ela não executa IA, altera o site nem publica código.</p></section>}</div></>;
}
