// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest';
import { act, createElement } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { LightboxContent } from '@/components/public/Lightbox';
import { initializePublicGalleries } from '@/components/public/galleries';
import { PublicInteractions } from '@/components/public/Interactions';

let reactRoot: Root | undefined;
const originalFullscreen = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'requestFullscreen');
afterEach(async () => { if (reactRoot) await act(async () => reactRoot?.unmount()); reactRoot = undefined; document.body.innerHTML = ''; vi.useRealTimers(); vi.unstubAllGlobals(); vi.restoreAllMocks(); if (originalFullscreen) Object.defineProperty(HTMLElement.prototype,'requestFullscreen',originalFullscreen); else Reflect.deleteProperty(HTMLElement.prototype,'requestFullscreen'); });
describe('source gallery controls', () => {
  it('switches the original table-of-contents expand and collapse state for keyboard use', async () => {
    vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT', true); vi.stubGlobal('matchMedia', () => ({ matches:false }));
    document.body.innerHTML = '<div class="public-site"><div class="elementor-widget-table-of-contents"><div class="elementor-toc__toggle-button elementor-toc__toggle-button--collapse" aria-label="Close table of contents"></div><div class="elementor-toc__toggle-button elementor-toc__toggle-button--expand" aria-label="Open table of contents"></div><div class="elementor-toc__body">Índice</div></div><div id="mount"></div></div>';
    reactRoot = createRoot(document.querySelector('#mount')!);
    await act(async () => reactRoot!.render(createElement(PublicInteractions, { popup:{ active:false, title:'', text:'', startsAt:null, endsAt:null, version:1, updatedAt:'' } })));
    const widget = document.querySelector('.elementor-widget-table-of-contents')!, collapse = widget.querySelector<HTMLElement>('.elementor-toc__toggle-button--collapse')!, expand = widget.querySelector<HTMLElement>('.elementor-toc__toggle-button--expand')!;
    await act(async () => collapse.dispatchEvent(new KeyboardEvent('keydown', { key:'Enter', bubbles:true, cancelable:true })));
    expect(widget.classList.contains('elementor-toc--collapsed')).toBe(true); expect(expand.getAttribute('aria-expanded')).toBe('false');
    await act(async () => expand.dispatchEvent(new KeyboardEvent('keydown', { key:'Enter', bubbles:true, cancelable:true })));
    expect(widget.classList.contains('elementor-toc--collapsed')).toBe(false); expect(collapse.getAttribute('aria-expanded')).toBe('true');
  });
  it('selects the clicked original image thumbnail, steps backwards and removes listeners on cleanup', () => {
    vi.stubGlobal('matchMedia', () => ({ matches: false }));
    document.body.innerHTML = '<div class="public-legacy-gallery" data-autoplay="false"><div class="sgb-gallery"><div class="sgb-item"></div><div class="sgb-item"></div><div class="sgb-item"></div></div><button class="public-gallery-thumb" data-gallery-index="0"></button><button class="public-gallery-thumb" data-gallery-index="1"></button><button class="public-gallery-thumb" data-gallery-index="2"></button><button class="public-gallery-prev"></button><button class="public-gallery-next"></button></div>';
    const strip = document.querySelector<HTMLElement>('.sgb-gallery')!;
    Object.defineProperty(strip, 'clientWidth', { value:100 }); Object.defineProperty(strip, 'scrollWidth', { value:300 });
    const scroll = vi.fn(); strip.scrollTo = scroll;
    document.querySelectorAll('.sgb-item').forEach((panel, index) => Object.defineProperty(panel, 'offsetLeft', { value: index * 100 }));
    const cleanup = initializePublicGalleries(document.body);
    const thumbs = document.querySelectorAll<HTMLButtonElement>('.public-gallery-thumb'); thumbs[2].click();
    expect(scroll).toHaveBeenLastCalledWith({ left: 200, behavior: 'smooth' }); expect(thumbs[2].getAttribute('aria-pressed')).toBe('true');
    document.querySelector<HTMLButtonElement>('.public-gallery-prev')!.click();
    expect(scroll).toHaveBeenLastCalledWith({ left: 100, behavior: 'smooth' }); expect(thumbs[1].getAttribute('aria-pressed')).toBe('true');
    strip.dispatchEvent(new Event('touchstart')); strip.scrollLeft = 200; strip.dispatchEvent(new Event('scroll'));
    expect(thumbs[2].getAttribute('aria-pressed')).toBe('true');
    strip.scrollLeft = 100; strip.dispatchEvent(new Event('scroll'));
    document.querySelector<HTMLButtonElement>('.public-gallery-next')!.click();
    expect(scroll).toHaveBeenLastCalledWith({ left: 200, behavior: 'smooth' });
    cleanup(); scroll.mockClear(); thumbs[0].click(); expect(scroll).not.toHaveBeenCalled();
    strip.scrollLeft = 0; strip.dispatchEvent(new Event('scroll')); expect(thumbs[2].getAttribute('aria-pressed')).toBe('true');
  });
  it('preserves the last thumbnail through programmatic clamping and loops the last desktop page in one step', () => {
    vi.stubGlobal('matchMedia', () => ({ matches:false }));
    document.body.innerHTML = `<div class="public-legacy-gallery" data-autoplay="false"><div class="sgb-gallery">${Array.from({ length:11 }, () => '<div class="sgb-item"></div>').join('')}</div>${Array.from({ length:11 }, (_, index) => `<button class="public-gallery-thumb" data-gallery-index="${index}"></button>`).join('')}<button class="public-gallery-next"></button></div>`;
    const strip = document.querySelector<HTMLElement>('.sgb-gallery')!;
    Object.defineProperty(strip, 'clientWidth', { value:300 }); Object.defineProperty(strip, 'scrollWidth', { value:1100 });
    document.querySelectorAll('.sgb-item').forEach((panel, index) => Object.defineProperty(panel, 'offsetLeft', { value:index*100 }));
    strip.scrollTo = vi.fn(options => { const next = Math.min(800, Math.max(0, (options as ScrollToOptions).left || 0)); if (strip.scrollLeft !== next) { strip.scrollLeft = next; strip.dispatchEvent(new Event('scroll')); } });
    const cleanup = initializePublicGalleries(document.body);
    const thumbs = document.querySelectorAll<HTMLButtonElement>('.public-gallery-thumb'); thumbs[10].click();
    expect(strip.scrollLeft).toBe(800); expect(thumbs[10].getAttribute('aria-pressed')).toBe('true');
    document.querySelector<HTMLButtonElement>('.public-gallery-next')!.click();
    expect(strip.scrollLeft).toBe(0); expect(thumbs[0].getAttribute('aria-pressed')).toBe('true');
    document.querySelector<HTMLButtonElement>('.public-gallery-next')!.click(); expect(strip.scrollLeft).toBe(300);
    cleanup();
  });
  it('uses the source four-second autoplay default and advances one full visible page', () => {
    vi.useFakeTimers(); vi.stubGlobal('matchMedia', () => ({ matches:false })); vi.spyOn(document, 'hidden', 'get').mockReturnValue(false);
    document.body.innerHTML = '<div class="public-legacy-gallery" data-autoplay="true"><div class="sgb-gallery"><div class="sgb-item"></div><div class="sgb-item"></div><div class="sgb-item"></div><div class="sgb-item"></div></div></div>';
    const strip = document.querySelector<HTMLElement>('.sgb-gallery')!, scroll = vi.fn(); strip.scrollTo = scroll;
    Object.defineProperty(strip, 'clientWidth', { value:300 }); Object.defineProperty(strip, 'scrollWidth', { value:400 });
    document.querySelectorAll('.sgb-item').forEach((panel, index) => Object.defineProperty(panel, 'offsetLeft', { value:index*100 }));
    const cleanup = initializePublicGalleries(document.body);
    vi.advanceTimersByTime(3999); expect(scroll).not.toHaveBeenCalled(); vi.advanceTimersByTime(1);
    expect(scroll).toHaveBeenLastCalledWith({ left:300, behavior:'smooth' });
    cleanup(); vi.useRealTimers();
  });
  it('ports source zoom, empty Share overlay, fullscreen and close without inventing sharing actions', async () => {
    vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT', true);
    const copy = vi.fn().mockResolvedValue(undefined); Object.defineProperty(navigator, 'clipboard', { value: { writeText: copy }, configurable: true });
    document.body.innerHTML = '<dialog></dialog>'; const dialog = document.querySelector('dialog')!;
    const fullscreen = vi.fn(function (this:HTMLElement) { return this.tagName === 'DIALOG' ? Promise.reject(new TypeError('Dialog cannot enter fullscreen')) : Promise.resolve(); });
    Object.defineProperty(HTMLElement.prototype, 'requestFullscreen', { configurable:true, value:fullscreen });
    const close = vi.fn(), move = vi.fn(); reactRoot = createRoot(dialog);
    await act(async () => reactRoot!.render(createElement(LightboxContent, { urls: ['https://clinic.example/photo.webp', 'https://clinic.example/second.webp'], index: 0, caption: 'Consultório', onClose: close, onMove: move })));
    const button = (label: string) => dialog.querySelector<HTMLButtonElement>(`button[aria-label="${label}"]`)!;
    expect(Array.from(dialog.querySelectorAll('.public-lightbox-toolbar button')).map(button => button.getAttribute('aria-label'))).toEqual(['Zoom', 'Share', 'Fullscreen', 'Close']);
    expect(copy).not.toHaveBeenCalled();
    const image = dialog.querySelector<HTMLImageElement>('.public-lightbox-stage img')!;
    Object.defineProperty(image, 'naturalWidth', { value:980 }); Object.defineProperty(image, 'naturalHeight', { value:523 });
    image.getBoundingClientRect = () => ({ width:980, height:523 }) as DOMRect;
    await act(async () => button('Zoom').click()); expect(dialog.querySelector('.public-lightbox-zoomed')).not.toBeNull();
    const stage = dialog.querySelector<HTMLElement>('.public-lightbox-stage')!;
    expect(image.style.width).toBe('1960px'); const initialLeft = stage.scrollLeft, initialTop = stage.scrollTop;
    await act(async () => { stage.dispatchEvent(new MouseEvent('pointerdown', { bubbles: true, clientX:100, clientY:100, button:0 })); stage.dispatchEvent(new MouseEvent('pointermove', { bubbles:true, clientX:80, clientY:70 })); stage.dispatchEvent(new MouseEvent('pointerup', { bubbles:true })); });
    expect(stage.scrollLeft).toBe(initialLeft + 20); expect(stage.scrollTop).toBe(initialTop + 30);
    await act(async () => button('Share').click()); expect(copy).not.toHaveBeenCalled();
    const share = dialog.querySelector<HTMLElement>('.public-lightbox-share')!;
    expect(share.querySelectorAll('button,a,input')).toHaveLength(0);
    await act(async () => dialog.dispatchEvent(new Event('cancel', { cancelable:true })));
    expect(dialog.querySelector('.public-lightbox-share')).toBeNull(); expect(close).not.toHaveBeenCalled();
    await act(async () => button('Fullscreen').click()); expect(fullscreen).toHaveBeenCalledOnce();
    expect(fullscreen.mock.contexts[0]?.tagName).toBe('DIV');
    expect(fullscreen.mock.contexts[0]?.contains(button('Close'))).toBe(true);
    expect(dialog.querySelector('[role="status"]')).toBeNull();
    await act(async () => button('Próxima imagem').click()); expect(move).toHaveBeenCalledWith(1);
    await act(async () => button('Close').click()); expect(close).toHaveBeenCalledOnce();
  });
  it('uses captured image captions and Escape dismisses Share before closing the gallery with focus restoration', async () => {
    vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT', true); vi.stubGlobal('matchMedia', () => ({ matches:false }));
    const originalShow = Object.getOwnPropertyDescriptor(HTMLDialogElement.prototype, 'showModal'), originalClose = Object.getOwnPropertyDescriptor(HTMLDialogElement.prototype, 'close');
    Object.defineProperty(HTMLDialogElement.prototype, 'showModal', { configurable:true, value:function (this:HTMLDialogElement) { this.open = true; } });
    Object.defineProperty(HTMLDialogElement.prototype, 'close', { configurable:true, value:function (this:HTMLDialogElement) { this.open = false; } });
    document.body.innerHTML = '<div class="public-site"><div class="sgb-gallery"><a href="https://clinic.example/first.webp" data-gallery-caption="Consultorio 2"><img alt=""></a><a href="https://clinic.example/second.webp" data-gallery-caption="Recepção"><img alt=""></a></div><div id="mount"></div></div>';
    const anchor = document.querySelector<HTMLAnchorElement>('.sgb-gallery a')!; anchor.focus();
    reactRoot = createRoot(document.querySelector('#mount')!);
    await act(async () => reactRoot!.render(createElement(PublicInteractions, { popup: { active:false, title:'', text:'', startsAt:null, endsAt:null, version:1, updatedAt:'' } })));
    await act(async () => anchor.click()); const dialog = document.querySelector('dialog')!;
    expect(dialog.open).toBe(true); expect(dialog.querySelector('.public-lightbox-caption')?.textContent).toBe('Consultorio 2');
    await act(async () => dialog.querySelector<HTMLButtonElement>('button[aria-label="Próxima imagem"]')!.click());
    expect(dialog.querySelector('.public-lightbox-caption')?.textContent).toBe('Recepção');
    await act(async () => dialog.querySelector<HTMLButtonElement>('button[aria-label="Share"]')!.click());
    await act(async () => dialog.dispatchEvent(new Event('cancel', { cancelable:true })));
    expect(dialog.open).toBe(true); expect(dialog.querySelector('.public-lightbox-share')).toBeNull();
    await act(async () => dialog.dispatchEvent(new Event('cancel', { cancelable:true })));
    expect(dialog.open).toBe(false); expect(document.activeElement).toBe(anchor);
    if (originalShow) Object.defineProperty(HTMLDialogElement.prototype, 'showModal', originalShow); else Reflect.deleteProperty(HTMLDialogElement.prototype, 'showModal');
    if (originalClose) Object.defineProperty(HTMLDialogElement.prototype, 'close', originalClose); else Reflect.deleteProperty(HTMLDialogElement.prototype, 'close');
  });
  it('hides zoom controls after the source three-second pointer delay and reveals them on movement', async () => {
    vi.useFakeTimers(); vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT', true);
    document.body.innerHTML = '<dialog></dialog>'; const dialog = document.querySelector('dialog')!;
    reactRoot = createRoot(dialog);
    await act(async () => reactRoot!.render(createElement(LightboxContent, { urls:['https://clinic.example/photo.webp'], index:0, caption:'Consultorio 2', onClose:vi.fn(), onMove:vi.fn() })));
    const image = dialog.querySelector<HTMLImageElement>('img')!;
    Object.defineProperty(image, 'naturalWidth', { value:980 }); Object.defineProperty(image, 'naturalHeight', { value:523 });
    image.getBoundingClientRect = () => ({ width:980, height:523 }) as DOMRect;
    await act(async () => dialog.querySelector<HTMLButtonElement>('[aria-label="Zoom"]')!.click());
    const header = dialog.querySelector('.public-lightbox-header')!;
    await act(async () => vi.advanceTimersByTime(2999)); expect(header.classList.contains('public-lightbox-controls-hidden')).toBe(false);
    await act(async () => vi.advanceTimersByTime(1)); expect(header.classList.contains('public-lightbox-controls-hidden')).toBe(true);
    await act(async () => dialog.dispatchEvent(new MouseEvent('mousemove', { bubbles:true })));
    expect(header.classList.contains('public-lightbox-controls-hidden')).toBe(false);
    await act(async () => vi.advanceTimersByTime(3000)); expect(header.classList.contains('public-lightbox-controls-hidden')).toBe(true);
    await act(async () => reactRoot!.unmount()); reactRoot = undefined;
    expect(vi.getTimerCount()).toBe(0);
  });
});
